from sqlalchemy import Column, String, Integer, Float, Boolean, Date, Text, DateTime
from sqlalchemy.dialects.postgresql import JSONB
from geoalchemy2 import Geometry
from app.db import Base
from datetime import datetime

class Project(Base):
    __tablename__ = 'projects'
    project_id = Column(String, primary_key=True, index=True)
    project_name = Column(String, nullable=False)
    project_type = Column(String, index=True)
    department = Column(String)
    state = Column(String, index=True)
    district = Column(String, index=True)
    tehsil = Column(String)
    village = Column(String)
    latitude = Column(Float)
    longitude = Column(Float)
    geom = Column(Geometry(geometry_type='POINT', srid=4326), nullable=True)
    land_area_hectares = Column(Float)
    affected_families = Column(Integer)
    affected_landowners = Column(Integer)
    acquisition_method = Column(String)
    notification_status = Column(String)
    notification_date = Column(String)
    award_date = Column(String)
    approval_status = Column(String)
    pending_approvals = Column(Integer)
    approval_delay_days = Column(Integer)
    compensation_total = Column(Integer)
    compensation_disbursed = Column(Integer)
    compensation_pending = Column(Integer)
    compensation_pending_percentage = Column(Integer)
    legal_disputes = Column(Integer)
    court_cases = Column(Integer)
    documentation_completeness = Column(Integer)
    ownership_conflicts = Column(Integer)
    possession_percentage = Column(Integer)
    rehabilitation_status = Column(String)
    rehabilitation_percentage = Column(Integer)
    stakeholder_responsiveness = Column(Integer)
    department_response_delay_days = Column(Integer)
    interdepartmental_dependencies = Column(Integer)
    previous_project_delay_rate = Column(Float)
    planned_completion_days = Column(Integer)
    elapsed_days = Column(Integer)
    extension_count = Column(Integer)
    grievance_count = Column(Integer)
    field_verification_status = Column(String)
    survey_completion_percentage = Column(Integer)
    utility_shift_status = Column(String)
    environmental_clearance_status = Column(String)
    forest_clearance_status = Column(String)
    r_and_r_pending_families = Column(Integer)
    officer_workload = Column(Integer)
    historical_district_delay_rate = Column(Float)
    current_stage = Column(String)
    actual_delay_days = Column(Integer)
    delayed = Column(Integer, index=True)
    extra = Column(JSONB)

class User(Base):
    __tablename__ = 'users'
    username = Column(String, primary_key=True, index=True)
    hashed_password = Column(String, nullable=False)
    role = Column(String, default='viewer')
    full_name = Column(String)
    email = Column(String)

class Alert(Base):
    __tablename__ = 'alerts'
    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(String, index=True)
    alert_type = Column(String)
    message = Column(Text)
    severity = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
    read = Column(Boolean, default=False)
    meta = Column(JSONB)

class AuditLog(Base):
    __tablename__ = 'audit_logs'
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String)
    action = Column(String)
    project_id = Column(String)
    old_value = Column(JSONB)
    new_value = Column(JSONB)
    timestamp = Column(DateTime, default=datetime.utcnow)
    meta = Column(JSONB)
